name: Update Changelog

on:
  pull_request:
    types: [synchronize, opened]

jobs:
  update-changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Update Changelog
        uses: ashwin-pc/test-github-action@vmain
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          changelog_path: CHANGELOG.md
