on: [pull_request]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Hello world action step
        id: hello
        uses: ashwin-pc/test-github-action@v1.1
        with:
          who-to-greet: "Mona the Octocat"
